[2024-09-02T23:54:12.708+0000] {processor.py:161} INFO - Started process (PID=218) to work on /opt/airflow/dags/dag_etl.py
[2024-09-02T23:54:12.710+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_etl.py for tasks to queue
[2024-09-02T23:54:12.716+0000] {logging_mixin.py:188} INFO - [2024-09-02T23:54:12.715+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_etl.py
[2024-09-02T23:54:12.759+0000] {logging_mixin.py:188} INFO - [2024-09-02T23:54:12.744+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_etl.py", line 3, in <module>
    from airflow  import PythonOperator
ImportError: cannot import name 'PythonOperator' from 'airflow' (/home/airflow/.local/lib/python3.12/site-packages/airflow/__init__.py)
[2024-09-02T23:54:12.763+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_etl.py
[2024-09-02T23:54:12.799+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_etl.py took 0.104 seconds
[2024-09-02T23:54:14.727+0000] {processor.py:161} INFO - Started process (PID=219) to work on /opt/airflow/dags/dag_etl.py
[2024-09-02T23:54:14.728+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_etl.py for tasks to queue
[2024-09-02T23:54:14.730+0000] {logging_mixin.py:188} INFO - [2024-09-02T23:54:14.729+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_etl.py
[2024-09-02T23:54:14.765+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_etl.py
[2024-09-02T23:54:14.780+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_etl.py took 0.059 seconds
[2024-09-02T23:54:34.924+0000] {processor.py:161} INFO - Started process (PID=226) to work on /opt/airflow/dags/dag_etl.py
[2024-09-02T23:54:34.925+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_etl.py for tasks to queue
[2024-09-02T23:54:34.928+0000] {logging_mixin.py:188} INFO - [2024-09-02T23:54:34.927+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_etl.py
[2024-09-02T23:54:34.953+0000] {logging_mixin.py:188} INFO - [2024-09-02T23:54:34.949+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_etl.py", line 3, in <module>
    from airflow.operators.python.PythonOperator import PythonOperator
ModuleNotFoundError: No module named 'airflow.operators.python.PythonOperator'; 'airflow.operators.python' is not a package
[2024-09-02T23:54:34.956+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_etl.py
[2024-09-02T23:54:34.981+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_etl.py took 0.066 seconds
[2024-09-02T23:55:05.109+0000] {processor.py:161} INFO - Started process (PID=233) to work on /opt/airflow/dags/dag_etl.py
[2024-09-02T23:55:05.111+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_etl.py for tasks to queue
[2024-09-02T23:55:05.113+0000] {logging_mixin.py:188} INFO - [2024-09-02T23:55:05.113+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_etl.py
[2024-09-02T23:55:05.131+0000] {logging_mixin.py:188} INFO - [2024-09-02T23:55:05.126+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_etl.py", line 3, in <module>
    from airflow.operators.python.PythonOperator import PythonOperator
ModuleNotFoundError: No module named 'airflow.operators.python.PythonOperator'; 'airflow.operators.python' is not a package
[2024-09-02T23:55:05.133+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_etl.py
[2024-09-02T23:55:05.162+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_etl.py took 0.060 seconds
[2024-09-02T23:55:35.343+0000] {processor.py:161} INFO - Started process (PID=240) to work on /opt/airflow/dags/dag_etl.py
[2024-09-02T23:55:35.343+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_etl.py for tasks to queue
[2024-09-02T23:55:35.346+0000] {logging_mixin.py:188} INFO - [2024-09-02T23:55:35.345+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_etl.py
[2024-09-02T23:55:35.360+0000] {logging_mixin.py:188} INFO - [2024-09-02T23:55:35.356+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_etl.py", line 3, in <module>
    from airflow.operators.python.PythonOperator import PythonOperator
ModuleNotFoundError: No module named 'airflow.operators.python.PythonOperator'; 'airflow.operators.python' is not a package
[2024-09-02T23:55:35.361+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_etl.py
[2024-09-02T23:55:35.390+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_etl.py took 0.052 seconds
[2024-09-02T23:55:42.395+0000] {processor.py:161} INFO - Started process (PID=241) to work on /opt/airflow/dags/dag_etl.py
[2024-09-02T23:55:42.396+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_etl.py for tasks to queue
[2024-09-02T23:55:42.398+0000] {logging_mixin.py:188} INFO - [2024-09-02T23:55:42.398+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_etl.py
[2024-09-02T23:55:42.413+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_etl.py
[2024-09-02T23:55:42.451+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_etl.py took 0.061 seconds
[2024-09-02T23:56:03.596+0000] {processor.py:161} INFO - Started process (PID=248) to work on /opt/airflow/dags/dag_etl.py
[2024-09-02T23:56:03.597+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_etl.py for tasks to queue
[2024-09-02T23:56:03.599+0000] {logging_mixin.py:188} INFO - [2024-09-02T23:56:03.599+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_etl.py
[2024-09-02T23:56:03.626+0000] {logging_mixin.py:188} INFO - [2024-09-02T23:56:03.621+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_etl.py", line 3, in <module>
    from airflow.operators.PythonOperator import PythonOperator
ModuleNotFoundError: No module named 'airflow.operators.PythonOperator'
[2024-09-02T23:56:03.628+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_etl.py
[2024-09-02T23:56:03.654+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_etl.py took 0.065 seconds
[2024-09-02T23:56:33.779+0000] {processor.py:161} INFO - Started process (PID=255) to work on /opt/airflow/dags/dag_etl.py
[2024-09-02T23:56:33.780+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_etl.py for tasks to queue
[2024-09-02T23:56:33.782+0000] {logging_mixin.py:188} INFO - [2024-09-02T23:56:33.782+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_etl.py
[2024-09-02T23:56:33.796+0000] {logging_mixin.py:188} INFO - [2024-09-02T23:56:33.792+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_etl.py", line 3, in <module>
    from airflow.operators.PythonOperator import PythonOperator
ModuleNotFoundError: No module named 'airflow.operators.PythonOperator'
[2024-09-02T23:56:33.798+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_etl.py
[2024-09-02T23:56:33.820+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_etl.py took 0.047 seconds
[2024-09-02T23:57:04.014+0000] {processor.py:161} INFO - Started process (PID=262) to work on /opt/airflow/dags/dag_etl.py
[2024-09-02T23:57:04.017+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_etl.py for tasks to queue
[2024-09-02T23:57:04.021+0000] {logging_mixin.py:188} INFO - [2024-09-02T23:57:04.020+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_etl.py
[2024-09-02T23:57:04.040+0000] {logging_mixin.py:188} INFO - [2024-09-02T23:57:04.034+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_etl.py", line 3, in <module>
    from airflow.operators.PythonOperator import PythonOperator
ModuleNotFoundError: No module named 'airflow.operators.PythonOperator'
[2024-09-02T23:57:04.041+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_etl.py
[2024-09-02T23:57:04.063+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_etl.py took 0.061 seconds
[2024-09-02T23:57:34.199+0000] {processor.py:161} INFO - Started process (PID=269) to work on /opt/airflow/dags/dag_etl.py
[2024-09-02T23:57:34.200+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_etl.py for tasks to queue
[2024-09-02T23:57:34.203+0000] {logging_mixin.py:188} INFO - [2024-09-02T23:57:34.202+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_etl.py
[2024-09-02T23:57:34.215+0000] {logging_mixin.py:188} INFO - [2024-09-02T23:57:34.212+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_etl.py", line 3, in <module>
    from airflow.operators.PythonOperator import PythonOperator
ModuleNotFoundError: No module named 'airflow.operators.PythonOperator'
[2024-09-02T23:57:34.217+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_etl.py
[2024-09-02T23:57:34.241+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_etl.py took 0.048 seconds
[2024-09-02T23:58:04.406+0000] {processor.py:161} INFO - Started process (PID=277) to work on /opt/airflow/dags/dag_etl.py
[2024-09-02T23:58:04.407+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_etl.py for tasks to queue
[2024-09-02T23:58:04.409+0000] {logging_mixin.py:188} INFO - [2024-09-02T23:58:04.409+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_etl.py
[2024-09-02T23:58:04.424+0000] {logging_mixin.py:188} INFO - [2024-09-02T23:58:04.421+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_etl.py", line 3, in <module>
    from airflow.operators.PythonOperator import PythonOperator
ModuleNotFoundError: No module named 'airflow.operators.PythonOperator'
[2024-09-02T23:58:04.425+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_etl.py
[2024-09-02T23:58:04.441+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_etl.py took 0.039 seconds
[2024-09-02T23:58:34.600+0000] {processor.py:161} INFO - Started process (PID=284) to work on /opt/airflow/dags/dag_etl.py
[2024-09-02T23:58:34.601+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_etl.py for tasks to queue
[2024-09-02T23:58:34.603+0000] {logging_mixin.py:188} INFO - [2024-09-02T23:58:34.603+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_etl.py
[2024-09-02T23:58:34.623+0000] {logging_mixin.py:188} INFO - [2024-09-02T23:58:34.618+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_etl.py", line 3, in <module>
    from airflow.operators.PythonOperator import PythonOperator
ModuleNotFoundError: No module named 'airflow.operators.PythonOperator'
[2024-09-02T23:58:34.625+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_etl.py
[2024-09-02T23:58:34.651+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_etl.py took 0.056 seconds
[2024-09-02T23:59:04.788+0000] {processor.py:161} INFO - Started process (PID=291) to work on /opt/airflow/dags/dag_etl.py
[2024-09-02T23:59:04.790+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_etl.py for tasks to queue
[2024-09-02T23:59:04.792+0000] {logging_mixin.py:188} INFO - [2024-09-02T23:59:04.792+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_etl.py
[2024-09-02T23:59:04.808+0000] {logging_mixin.py:188} INFO - [2024-09-02T23:59:04.804+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_etl.py", line 3, in <module>
    from airflow.operators.PythonOperator import PythonOperator
ModuleNotFoundError: No module named 'airflow.operators.PythonOperator'
[2024-09-02T23:59:04.810+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_etl.py
[2024-09-02T23:59:04.830+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_etl.py took 0.049 seconds
[2024-09-02T23:59:35.034+0000] {processor.py:161} INFO - Started process (PID=298) to work on /opt/airflow/dags/dag_etl.py
[2024-09-02T23:59:35.035+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_etl.py for tasks to queue
[2024-09-02T23:59:35.038+0000] {logging_mixin.py:188} INFO - [2024-09-02T23:59:35.037+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_etl.py
[2024-09-02T23:59:35.050+0000] {logging_mixin.py:188} INFO - [2024-09-02T23:59:35.048+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_etl.py", line 3, in <module>
    from airflow.operators.PythonOperator import PythonOperator
ModuleNotFoundError: No module named 'airflow.operators.PythonOperator'
[2024-09-02T23:59:35.052+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_etl.py
[2024-09-02T23:59:35.071+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_etl.py took 0.042 seconds
