[2024-09-03T02:16:46.985+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-09-03T02:16:46.999+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: redshift_etl_dag.extrear_datos_API scheduled__2024-09-02T00:00:00+00:00 [queued]>
[2024-09-03T02:16:47.006+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: redshift_etl_dag.extrear_datos_API scheduled__2024-09-02T00:00:00+00:00 [queued]>
[2024-09-03T02:16:47.008+0000] {taskinstance.py:2306} INFO - Starting attempt 3 of 6
[2024-09-03T02:16:47.019+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extrear_datos_API> on 2024-09-02 00:00:00+00:00
[2024-09-03T02:16:47.024+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=159) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-03T02:16:47.026+0000] {standard_task_runner.py:63} INFO - Started process 163 to run task
[2024-09-03T02:16:47.026+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'redshift_etl_dag', 'extrear_datos_API', 'scheduled__2024-09-02T00:00:00+00:00', '--job-id', '25', '--raw', '--subdir', 'DAGS_FOLDER/dag_etl.py', '--cfg-path', '/tmp/tmpdaod35jf']
[2024-09-03T02:16:47.029+0000] {standard_task_runner.py:91} INFO - Job 25: Subtask extrear_datos_API
[2024-09-03T02:16:47.095+0000] {task_command.py:426} INFO - Running <TaskInstance: redshift_etl_dag.extrear_datos_API scheduled__2024-09-02T00:00:00+00:00 [running]> on host d6a54f99c9c8
[2024-09-03T02:16:47.214+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='jose_araya' AIRFLOW_CTX_DAG_ID='redshift_etl_dag' AIRFLOW_CTX_TASK_ID='extrear_datos_API' AIRFLOW_CTX_EXECUTION_DATE='2024-09-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-02T00:00:00+00:00'
[2024-09-03T02:16:47.217+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-09-03T02:16:47.245+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-09-03T02:16:47.246+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: API.getdata() missing 1 required positional argument: 'self'
[2024-09-03T02:16:47.261+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=redshift_etl_dag, task_id=extrear_datos_API, run_id=scheduled__2024-09-02T00:00:00+00:00, execution_date=20240902T000000, start_date=20240903T021647, end_date=20240903T021647
[2024-09-03T02:16:47.276+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 25 for task extrear_datos_API (API.getdata() missing 1 required positional argument: 'self'; 163)
[2024-09-03T02:16:47.322+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-09-03T02:16:47.349+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-03T02:16:47.351+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
