[2024-09-03T02:13:45.317+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-09-03T02:13:45.332+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: redshift_etl_dag.extrear_datos_API manual__2024-09-03T02:10:38.592145+00:00 [queued]>
[2024-09-03T02:13:45.338+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: redshift_etl_dag.extrear_datos_API manual__2024-09-03T02:10:38.592145+00:00 [queued]>
[2024-09-03T02:13:45.338+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 6
[2024-09-03T02:13:45.349+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extrear_datos_API> on 2024-09-03 02:10:38.592145+00:00
[2024-09-03T02:13:45.355+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=112) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-03T02:13:45.356+0000] {standard_task_runner.py:63} INFO - Started process 115 to run task
[2024-09-03T02:13:45.357+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'redshift_etl_dag', 'extrear_datos_API', 'manual__2024-09-03T02:10:38.592145+00:00', '--job-id', '23', '--raw', '--subdir', 'DAGS_FOLDER/dag_etl.py', '--cfg-path', '/tmp/tmp96wkom8c']
[2024-09-03T02:13:45.359+0000] {standard_task_runner.py:91} INFO - Job 23: Subtask extrear_datos_API
[2024-09-03T02:13:45.412+0000] {task_command.py:426} INFO - Running <TaskInstance: redshift_etl_dag.extrear_datos_API manual__2024-09-03T02:10:38.592145+00:00 [running]> on host d6a54f99c9c8
[2024-09-03T02:13:45.507+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='jose_araya' AIRFLOW_CTX_DAG_ID='redshift_etl_dag' AIRFLOW_CTX_TASK_ID='extrear_datos_API' AIRFLOW_CTX_EXECUTION_DATE='2024-09-03T02:10:38.592145+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-03T02:10:38.592145+00:00'
[2024-09-03T02:13:45.509+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-09-03T02:13:45.525+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-09-03T02:13:45.526+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: API.getdata() missing 1 required positional argument: 'self'
[2024-09-03T02:13:45.537+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=redshift_etl_dag, task_id=extrear_datos_API, run_id=manual__2024-09-03T02:10:38.592145+00:00, execution_date=20240903T021038, start_date=20240903T021345, end_date=20240903T021345
[2024-09-03T02:13:45.553+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 23 for task extrear_datos_API (API.getdata() missing 1 required positional argument: 'self'; 115)
[2024-09-03T02:13:45.571+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-09-03T02:13:45.593+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-03T02:13:45.596+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
