[2024-09-03T02:32:09.898+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-09-03T02:32:09.914+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: redshift_etl_dag.cargar_datos manual__2024-09-03T02:10:38.592145+00:00 [queued]>
[2024-09-03T02:32:09.921+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: redshift_etl_dag.cargar_datos manual__2024-09-03T02:10:38.592145+00:00 [queued]>
[2024-09-03T02:32:09.922+0000] {taskinstance.py:2306} INFO - Starting attempt 4 of 6
[2024-09-03T02:32:09.936+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): cargar_datos> on 2024-09-03 02:10:38.592145+00:00
[2024-09-03T02:32:09.943+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=119) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-03T02:32:09.944+0000] {standard_task_runner.py:63} INFO - Started process 122 to run task
[2024-09-03T02:32:09.944+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'redshift_etl_dag', 'cargar_datos', 'manual__2024-09-03T02:10:38.592145+00:00', '--job-id', '44', '--raw', '--subdir', 'DAGS_FOLDER/dag_etl.py', '--cfg-path', '/tmp/tmps00xovz1']
[2024-09-03T02:32:09.948+0000] {standard_task_runner.py:91} INFO - Job 44: Subtask cargar_datos
[2024-09-03T02:32:09.997+0000] {task_command.py:426} INFO - Running <TaskInstance: redshift_etl_dag.cargar_datos manual__2024-09-03T02:10:38.592145+00:00 [running]> on host 117a0e03c003
[2024-09-03T02:32:10.085+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='jose_araya' AIRFLOW_CTX_DAG_ID='redshift_etl_dag' AIRFLOW_CTX_TASK_ID='cargar_datos' AIRFLOW_CTX_EXECUTION_DATE='2024-09-03T02:10:38.592145+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-03T02:10:38.592145+00:00'
[2024-09-03T02:32:10.088+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-09-03T02:32:10.123+0000] {python.py:237} INFO - Done. Returned value was: <modules.cargar_data.carga_datos object at 0x7f4b0435df70>
[2024-09-03T02:32:10.124+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-09-03T02:32:10.130+0000] {xcom.py:675} ERROR - Object of type carga_datos is not JSON serializable. If you are using pickle instead of JSON for XCom, then you need to enable pickle support for XCom in your *** config or make sure to decorate your object with attr.
[2024-09-03T02:32:10.131+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/json.py", line 91, in default
    return serialize(o)
           ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/serialization/serde.py", line 189, in serialize
    raise TypeError(f"cannot serialize object of type {cls}")
TypeError: cannot serialize object of type <class 'modules.cargar_data.carga_datos'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 486, in _execute_task
    task_instance.xcom_push(key=XCOM_RETURN_KEY, value=xcom_value, session=session)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3197, in xcom_push
    XCom.set(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/xcom.py", line 246, in set
    value = cls.serialize_value(
            ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/xcom.py", line 673, in serialize_value
    return json.dumps(value, cls=XComEncoder).encode("UTF-8")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/json.py", line 104, in encode
    return super().encode(o)
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/json.py", line 93, in default
    return super().default(o)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type carga_datos is not JSON serializable
[2024-09-03T02:32:10.146+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=redshift_etl_dag, task_id=cargar_datos, run_id=manual__2024-09-03T02:10:38.592145+00:00, execution_date=20240903T021038, start_date=20240903T023209, end_date=20240903T023210
[2024-09-03T02:32:10.164+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 44 for task cargar_datos (Object of type carga_datos is not JSON serializable; 122)
[2024-09-03T02:32:10.200+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-09-03T02:32:10.217+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-03T02:32:10.219+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
