[2024-09-03T02:41:49.358+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-09-03T02:41:49.370+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: redshift_etl_dag.cargar_datos manual__2024-09-03T02:38:39.287815+00:00 [queued]>
[2024-09-03T02:41:49.378+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: redshift_etl_dag.cargar_datos manual__2024-09-03T02:38:39.287815+00:00 [queued]>
[2024-09-03T02:41:49.379+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 6
[2024-09-03T02:41:49.392+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): cargar_datos> on 2024-09-03 02:38:39.287815+00:00
[2024-09-03T02:41:49.397+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=63) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-03T02:41:49.399+0000] {standard_task_runner.py:63} INFO - Started process 65 to run task
[2024-09-03T02:41:49.399+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'redshift_etl_dag', 'cargar_datos', 'manual__2024-09-03T02:38:39.287815+00:00', '--job-id', '56', '--raw', '--subdir', 'DAGS_FOLDER/dag_etl.py', '--cfg-path', '/tmp/tmpzb5lb8_6']
[2024-09-03T02:41:49.402+0000] {standard_task_runner.py:91} INFO - Job 56: Subtask cargar_datos
[2024-09-03T02:41:49.450+0000] {task_command.py:426} INFO - Running <TaskInstance: redshift_etl_dag.cargar_datos manual__2024-09-03T02:38:39.287815+00:00 [running]> on host d23b06e4b072
[2024-09-03T02:41:49.519+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='jose_araya' AIRFLOW_CTX_DAG_ID='redshift_etl_dag' AIRFLOW_CTX_TASK_ID='cargar_datos' AIRFLOW_CTX_EXECUTION_DATE='2024-09-03T02:38:39.287815+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-03T02:38:39.287815+00:00'
[2024-09-03T02:41:49.520+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-09-03T02:41:49.558+0000] {base.py:84} INFO - Using connection ID 'redshift_default' for task execution.
[2024-09-03T02:41:49.859+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/sqlalchemy_redshift/commands.py:31: SyntaxWarning: invalid escape sequence '\-'
  IAM_ROLE_NAME_RE = re.compile('[A-Za-z0-9+=,.@\-_]{1,64}')  # noqa

[2024-09-03T02:41:49.861+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/sqlalchemy_redshift/commands.py:33: SyntaxWarning: invalid escape sequence '\-'
  '[0-9]{12}:role/[A-Za-z0-9+=,.@\-_]{1,64}')  # noqa

[2024-09-03T02:41:49.875+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-09-03T02:41:49.876+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag_etl.py", line 13, in carga_datos_task
    carga_datos_instanciado.carga_datos()
  File "/opt/airflow/dags/modules/cargar_data.py", line 13, in carga_datos
    df = pd.read_csv('/opt/airflow/dags/temp/df_pandas.csv')
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 948, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 611, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1448, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1705, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 863, in get_handle
    handle = open(
             ^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/dags/temp/df_pandas.csv'
[2024-09-03T02:41:49.893+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=redshift_etl_dag, task_id=cargar_datos, run_id=manual__2024-09-03T02:38:39.287815+00:00, execution_date=20240903T023839, start_date=20240903T024149, end_date=20240903T024149
[2024-09-03T02:41:49.912+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 56 for task cargar_datos ([Errno 2] No such file or directory: '/opt/airflow/dags/temp/df_pandas.csv'; 65)
[2024-09-03T02:41:49.935+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-09-03T02:41:49.951+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-03T02:41:49.954+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
